version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: vcpkg
    directory: /requests_cpp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - vcpkg
    commit-message:
      prefix: "deps"
      include: scope
    groups:
      vcpkg-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
