#!/usr/bin/env python3
"""
Convert PEM certificate bundle to C++ header file.
Usage: python pem_to_header.py input.pem output.hpp
"""

import sys
import os
from datetime import datetime

def escape_string(s):
    """Escape a string for C++ source code."""
    result = []
    for line in s.split('\n'):
        if line:
            escaped = line.replace('\\', '\\\\').replace('"', '\\"')
            result.append(f'"{escaped}\\n"')
    return '\n'.join(result)

def convert_pem_to_header(input_path, output_path):
    """Convert PEM file to C++ header."""
    with open(input_path, 'r', encoding='utf-8') as f:
        pem_content = f.read()
    
    cert_count = pem_content.count('-----BEGIN CERTIFICATE-----')
    
    header = f"""// Auto-generated by pem_to_header.py
// Source: Mozilla NSS Root Certificate Store
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Certificate count: {cert_count}
// Total size: {len(pem_content)} bytes
//
// DO NOT EDIT THIS FILE MANUALLY
// To update: python scripts/pem_to_header.py root_certs.pem root_certs.hpp

#pragma once

#include <cstddef>

namespace requests_cpp::tls {{

// Embedded root certificates in PEM format
// Extracted from Mozilla NSS trust store
constexpr const char kEmbeddedRootCertsPem[] =
"""

    footer = """;

constexpr const std::size_t kEmbeddedRootCertsSize = sizeof(kEmbeddedRootCertsPem) - 1;

}  // namespace requests_cpp::tls
"""

    escaped_content = escape_string(pem_content)
    
    with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
        f.write(escaped_content)
        f.write(footer)
    
    print(f"Generated {output_path}")
    print(f"  Certificates: {cert_count}")
    print(f"  Source size: {len(pem_content)} bytes")
    print(f"  Output size: {os.path.getsize(output_path)} bytes")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} input.pem output.hpp")
        sys.exit(1)
    
    convert_pem_to_header(sys.argv[1], sys.argv[2])
